version: "3"
services:
  hermes:
    build:
      context: ./hermes  # Docker context from folder of this file; needed to include requirement.txt
      dockerfile: Dockerfile
     # map container interal 5550 port to publicly accessible 5550 port
    # stdin_open: true  # same as docker -i (interactive)
    tty: true  # same as docker -t (tty); see if sub actually receives pub messages
    command: ["python", "main.py", "--ip", "zeus"]  # sub module binds, so no need for a specific IP