apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: hermes
  name: hermes
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hermes
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: hermes
    spec:
      containers:
      - args:
        - python
        - main.py
        - --ip
        - zeus
        image: hermes
        imagePullPolicy: ""
        name: hermes
        resources: {}
        tty: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
