apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: zeus
  name: zeus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zeus
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: zeus
    spec:
      containers:
      - args:
        - python
        - main.py
        - --ip
        - 0.0.0.0
        image: zeus
        imagePullPolicy: ""
        name: zeus
        ports:
        - containerPort: 6000
        - containerPort: 6001
        resources: {}
        tty: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
