apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: zeus
  name: zeus
spec:
  ports:
  - name: "6000"
    port: 6000
    targetPort: 6000
  - name: "6001"
    port: 6001
    targetPort: 6001
  selector:
    io.kompose.service: zeus
status:
  loadBalancer: {}
