version: "3"
services:
  ares:
    build:
      context: ./ares
      dockerfile: Dockerfile
    # stdin_open: true  # same as docker -i (interactive)
    tty: true  # same as docker -t (tty); see if pub actually publishes messages to sub
    command: ["python", "main.py", "--ip", "zeus"]  # pub module connects, therefore sub Docker IP needed